version: 2

sources:
  - name: nyc_taxi
    database: bigquery-public-data
    schema: new_york_taxi_trips
    tables:
      - name: tlc_yellow_trips_2022
      - name: tlc_green_trips_2022
      - name: taxi_zone_geom       